socialteambuilder/accounts/urls.py
# accounts/urls.py

from django.urls import path, re_path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.Register.as_view(), name="register"),
    path('login/', views.LogIn.as_view(), name='login'),
    re_path('check-inbox/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', views.CheckInbox.as_view(), name="check_inbox"),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    path('updateuser/', views.update_user, name="updateuser"),
    path('profile/<int:pk>/', views.Profile.as_view(), name="profile"),
]

socialteambuilder/projects/urls.py
# project urls.py

from django.urls import path, re_path
from . import views

app_name = 'projects'

urlpatterns = [
    path('search/', views.SearchBar.as_view(), name='searchbar'),
    path('dashboard/<category>/<q>/', views.DashboardView.as_view(), name='dashboard'),
    path('applications/<box>/<category>/<q>/', views.ApplicationsList.as_view(), name='applications'),
    path('ajax/update_app_status/', views.UpdateAppStatus.as_view(), name='update_app_status'),
    path('ajax/create_app/', views.CreateApp.as_view(), name='newapp'),
    path('detail/<slug>/', views.ProjectView.as_view(), name='project'),
    path('delete_project/<slug>/', views.DeleteProject.as_view(), name='delete_project'),
    re_path(r'^create-update-project/(?:(?P<slug>[-a-zA-Z0-9]+)/)?$', views.create_update_project, name="create_update_project"),
]

socialteambuilder/socialteambuilder/urls.py
import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from markdownx import urls as markdownx

from .views import RootRedirect

urlpatterns = [
    path('', RootRedirect.as_view()),
    path('adminymin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('select2/', include('django_select2.urls')),
    path('markdownx/', include(markdownx))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

socialteambuilder/projects/models.py
from django.conf import settings
from django.db import models
from django.utils.text import slugify
from django.utils import timezone


class Project(models.Model):
    """Model representing a development project that users can create
    and/or join
    """
    STATUS = [
        ('A', 'Open'),
        ('B', 'Closed'),
        ('C', 'Complete'),
    ]
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="projects"
    )
    title = models.CharField(max_length=255, unique=True)
    description = models.TextField(max_length=2000)
    time_estimate = models.IntegerField()
    applicant_requirements = models.TextField(max_length=2000)
    status = models.CharField(max_length=1, choices=STATUS)
    created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(blank=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # set the slug
        self.slug = slugify(self.title, allow_unicode=True)
        # set project status based on existance of related positons
        super().save(*args, **kwargs)


class Position(models.Model):
    """Model representing a single position within a developing project
    that users can apply to
    """
    STATUS = (
        ('E', 'Empty'),
        ('F', 'Filled')
    )
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=2000)
    skills = models.ManyToManyField('accounts.Skill', related_name="positions")
    status = models.CharField(max_length=1, choices=STATUS)
    time_estimate = models.IntegerField()
    slug = models.SlugField(editable=False, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)


class Application(models.Model):
    """Model representing a user's application to a project's
    position
    """
    STATUS = (
        ('A', 'Accepted'),
        ('R', 'Declined'),
        ('U', 'Undecided')
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="applications"
    )
    position = models.ForeignKey(
        'Position',
        on_delete=models.CASCADE,
        related_name="applications"
    )
    status = models.CharField(max_length=1, choices=STATUS)
    unread = models.NullBooleanField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True) #auto_now_add=True

    def __str__(self):
        if self.status in ('A', 'R'):
            return "{} was {} for {}".format(
                self.user.first_name,
                dict(self.STATUS)[self.status],
                self.position
            )
        return "{} applied to {}".format(
            self.user.first_name,
            self.position.title
        )

    class Meta:
        unique_together = ['user', 'position']
        ordering = ['-created']

socialteambuilder/projects/views.py
# projects/views

from braces.views import PrefetchRelatedMixin

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.db.models import Q
from django.http import (
    JsonResponse,
    HttpResponseBadRequest,
    HttpResponseServerError,
    HttpResponseRedirect,
    Http404
)
from django.shortcuts import render, get_object_or_404, reverse
from django.urls import reverse_lazy
from django.views.generic import View, DetailView, DeleteView, CreateView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.list import ListView

from .models import Application, Project, Position
from .forms import CreateProjectForm, PositionFormset, SearchBarForm

User = get_user_model()

class OwnerMixin:
    """ Check if requesting user is owner of object or is a superuser
    """

    def dispatch(self, request, *args, **kwargs):
        if self.get_object().owner == request.user or request.user.is_admin:
            return super().dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


class CustomLoginRequired(LoginRequiredMixin):
    """Custom mixin that inherits LoginRequiredMixin funcitonality but
    also overlays a pending message delivery feature.
    """

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        apps = Application.objects.filter(
            user=request.user,
            unread=True,
        )
        if apps.exists():
            for app in apps:
                messages.success(
                    request,
                    "You've been {} for the position of {}, {}.".format(
                        app.get_status_display().lower(),
                        app.position.title,
                        app.position.project.title
                    ))
                app.unread = False
                app.save()
        return super().dispatch(request, *args, **kwargs)


class DashboardView(CustomLoginRequired, ListView):
    """View for all open projects
    """
    queryset = Project.objects.all()
    template_name = 'projects/dashboard.html'
    paginate_by = 5

    def get_queryset(self, *args, **kwargs):
        """get distinct projects that are currently open and have empty
        positions
        """
        super().get_queryset(*args, **kwargs)
        queryset = self.queryset.filter(
            status='A',
            position__status='E'
        ).distinct()
        category = self.kwargs['category']
        q = self.kwargs['q']
        if q != 'all':
            if category == 'need':
                queryset = queryset.filter(
                    position__slug=q
                )
            elif category == 'skill':
                queryset = queryset.filter(
                    position__skills__name=q
                )
            elif category == 'skills':
                not_user_positions = Position.objects.exclude(
                    applications__user=self.request.user
                )
                queryset = queryset.filter(
                    Q(position__skills__in=self.request.user.skills.all()) &
                    Q(position__in=[position for position in not_user_positions])
                )
            elif category == 'my-opps':
                not_user_positions = Position.objects.exclude(
                    applications__user=self.request.user
                )
                queryset = queryset.filter(
                    position__in=[position for position in not_user_positions]
                )
            elif category == 'accepted':
                queryset = queryset.filter(
                    Q(position__applications__user=self.request.user) &
                    Q(position__applications__status='R')
                )
        print(queryset)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['searchform'] = SearchBarForm()
        context['q'] = self.kwargs['q']
        return context


class SearchBar(CustomLoginRequired, ListView):
    """View that handles queries submitted by the SearchForm
    """
    queryset = Project.objects.all()
    template_name = 'projects/dashboard.html'
    paginate_by = 5

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        if request.GET.get('q') is not None:
            request.session['q'] = request.GET.get('q')
        self.q = request.session['q']
        print(self.q)

    def get_queryset(self, *args, **kwargs):
        """get distinct projects that are currently open and have empty
        positions
        """
        super().get_queryset(*args, **kwargs)
        queryset = self.queryset.filter(
            status='A',
            position__status='E'
        ).distinct()
        q = self.q
        queryset = queryset.filter(
            Q(title__icontains=q) |
            Q(description__icontains=q) |
            Q(applicant_requirements__icontains=q) |
            Q(position__title__icontains=q) |
            Q(position__skills__name__icontains=q)
        )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['searchform'] = SearchBarForm(initial={'q': self.q})
        context['query'] = self.q
        return context


class ApplicationsList(CustomLoginRequired, ListView):
    """View that displays all applications to the user's projects and
    any applications from the user to other user's projects
    """
    model = Application
    paginate_by = 5

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(
            Q(position__project__owner=self.request.user) |
            Q(user=self.request.user)
        ).select_related(
            'position', 'user'
        ).distinct()
        box = self.kwargs['box']
        if box == 'inbox':
            queryset = queryset.filter(
                position__project__owner=self.request.user
            )
        elif box == 'outbox':
            queryset = queryset.filter(
                user=self.request.user
            )
        category = self.kwargs['category']
        q = self.kwargs['q']
        if q != 'all':
            if category == 'status':
                queryset = queryset.filter(
                    status__icontains=q
                )
            elif category == 'project':
                queryset = queryset.filter(
                    position__project__slug=q
                )
            elif category == 'need':
                queryset = queryset.filter(
                    position__slug=q
                )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  
        context['searchform'] = SearchBarForm()
        context['q'] = self.kwargs['q']
        context['box'] = self.kwargs['box']
        context['inbox_count'] = self.get_queryset().filter(
            status='U',
            position__project__owner=self.request.user
        ).count()
        return context


class UpdateAppStatus(CustomLoginRequired, SingleObjectMixin, View):
    """View that handles ajax requests for changing the status of an
    application
    """
    model = Application
    http_method_names = ['post']

    def render_json_response(self, message, success):
        return JsonResponse({
            "message": message,
            "success": success
        })

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.kwargs.update({"pk": request.POST.get('app_pk')})

    def get_object(self):
        application = super().get_object()
        if application.position.project.owner != self.request.user:
            raise PermissionDenied
        return application

    def position_is_filled(self):
        app = self.get_object()
        return app.position.status == 'F'

    def update_app_status(self, status, unread):
        app = self.get_object()
        app.status = status
        app.unread = unread
        app.save()

    def update_outstanding_apps(self):
        app = self.get_object()
        outstanding = Application.objects.filter(
                position=app.position,
                status='U'
            )
        for app in outstanding:
            app.status = 'R'
            app.unread = True
            app.save()

    def post(self, request, *args, **kwargs):
        if self.position_is_filled():
            return self.render_json_response("Position is filled", False)
        status = self.request.POST.get('status')
        user = self.request.user
        app = self.get_object()
        position = app.position
        if status == 'A':
            self.update_app_status(status, True)
            position.status = 'F'
            position.save()
            self.update_outstanding_apps()
            # get refreshed app from db
            app = self.get_object()
            return self.render_json_response(app.get_status_display(), True)
        elif status == 'R':
            self.update_app_status(status, True)
            return self.render_json_response(app.get_status_display(), True)
        return self.render_json_response("Invalid or missing status", False)


class CreateApp(CustomLoginRequired, View):
    """View for handling ajax requests to create applications for requesting
    user and returning a jsonResponse
    """
    http_method_names = ['post']
    model = Application

    def render_json_response(self, message, success, status):
        return JsonResponse({
            "message": message,
            "success": success

socialteambuilder/projects/templates/projects/dashboard.html
{% extends 'layout.html' %}

{% load static %}
{% load project_extras %}

{% block messages %}
{{ block.super }}
{% endblock %}

{% block body %}
<div class="bounds">
<div class="top-button-container">
    <a class="bubble-dark" href="{% url 'projects:create_update_project' %}">
        <i class="fas fa-plus"></i>
        New Project
    </a>
  </div>
</div>

<div class="bounds">
<h2 class="h2-less-margin">Projects Dashboard</h2>
<p>find and filter projects to join here</p>
</div>

    <div class="bounds">
      <div class="desktop-wrapper">
        <div class="desktop-wrapper-left">
    <div class="card">
          <h4 class="">Project Needs</h4>
          <ul class="ul-list">
            {% if object_list %}
            {% select_distinct_positions_from_projects as titles %}
            <li class="bubble-outline {% if q == 'all' %}selected{% endif %}"><a 
                href="{% url 'projects:dashboard' category='all' q='all' %}">All Needs</a></li>
            {% for title in titles %}
            <li class="bubble-outline {% if q == title|slugify %}selected{% endif %}"><a 
                href="{% url 'projects:dashboard' category='need' q=title|slugify %}">{{ title }}</a></li>
            {% endfor %}
            {% endif %}
          </ul>
    </div>
    
          <div class="card">
              <h4 class="">Personalized</h4>
              <ul class="ul-list">
                <li class="bubble-outline {% if q == 'my-skills' %}class="selected" {% endif %}"><a 
                    href="{% url 'projects:dashboard' category='skills' q='my-skills' %}">Skills Match</a>
                </li>
                <li class="bubble-outline {% if q == 'my-opps' %}class="selected" {% endif %}"><a 
                    href="{% url 'projects:dashboard' category='my-opps' q='my-opps' %}">Open to Apply</a>
                </li>
                <li class="bubble-outline {% if q == 'accepted' %}class="selected" {% endif %}"><a 
                  href="{% url 'projects:dashboard' category='accepted' q='accepted' %}">Accepted</a>
              </li>
              </ul>
          </div>
        </div> <!-- desktop-wrapper-left -->

        <div class="desktop-wrapper-right">
  
      <div class="card">
          
        <div class="projects-header">
          <h4>Projects</h4>
        </div>
        {% if object_list %}
        <div class="desktop-flex-wrapper">
          {% for project in page_obj %}
            
            <a href="{% url 'projects:project' slug=project.slug %}">
              <div class="mini-card">
                  <h4 class="margin-bottom-0">{{ project.title|title }}</h4>
                  {% with project.position_set.all|length as length %}
                  {{ project.position_set.all|join:", " }}
                  {% if length > 3 %}and {{ project.position_set.all|slice:"3:"|length }} more...
                  {% endif %}
                  {% endwith %}
                </div>
            </a>
          
            {% endfor %}
            <a href=""><div class="project-card hidden"></div></a>
            <a href=""><div class="project-card hidden"></div></a>
            
            <div class="pagination">
              <span class="step-links">
                  {% if page_obj.has_previous %}
                      <a href="?page=1"><i class="fas fa-angle-double-left"></i> first </a>
                      <a href="?page={{ page_obj.previous_page_number }}"> previous </a>
                  {% endif %}
          
                  <span class="current">
                      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                  </span>
          
                  {% if page_obj.has_next %}
                      <a href="?page={{ page_obj.next_page_number }}"> next </i></a>
                      <a href="?page={{ page_obj.paginator.num_pages }}"> last <i class="fas fa-angle-double-right"></i></a>
                  {% endif %}
              </span>
          </div>
          
            {% else %}
            
              <div class="bounds">
                <div class="desktop-container">
                  <div class="mini-card">
                  <p>There are no {% if query %}<i>"{{ query }}"</i>{% endif%} projects here</p> 
              </div>
            </div>
            {% endif %}
          </div>
          </div>
      </div> 
    </div> <!-- desktop-wrapper-right -->
    </div> <!-- /desktop-wrapper-->
</div> <!-- /bounds-->

{% endblock %}

{% block js %}
{{ block.super }}

<script>
  const searchBar = document.getElementById('id_q');

  if ( searchBar.value ) {
    searchBar.style.color = '#8875ff';
    searchBar.style.fontWeight = 'bold';
  }
</script>

{% endblock %}

socialteambuilder/projects/templates/projects/project.html
{% extends 'layout.html' %}

{% block messages %}
{{ block.super }}
{% endblock %}

{% load project_extras %}
{% csrf_token %}

{% block body %}

<!-- Top Buttons -->
{% if project.owner == user %}
  <div class="bounds">
    <div class="top-button-container">
      <a class="bubble-dark" href="{% url 'projects:create_update_project' slug=project.slug %}">Edit Project</a>
      <a class="bubble-dark" href="{% url 'projects:delete_project' slug=project.slug %}">Delete Project</a>
    </div>
  </div>
  {% endif %}

          <div class="bounds">
            <div class="desktop-wrapper">
              <div class="desktop-wrapper-left">
              <div class="card">
                  <h2 class="">{{ project.title }}</h2>
                  <p class="">Project Owner: <a>{{ project.owner }}</a></p>
                  <p>Project Status: 
                    {% if project.status == 'A' %}
                    <span class="status-{{ project.status }}">Open</span> 
                    {% elif project.status == 'B' %}
                    <span class="status-{{ project.status }}">Closed</span> 
                    {% elif project.status == 'C' %}
                    <span class="status-{{ project.status }}">Complete</span> 
                    {% endif %}
                  </p>
                </div>
        
                <div class="card">
                    <h3>Project Description</h3>
                    {{ project.description }}
                  </div>
        
                <div class="card">
                    <h3>Project Needs</h3>
                    <ul class="ul-list">
                      {% select_distinct_positions_from_project_position_set as titles %}
                      {% for title in titles %}
                      <li class="bubble-outline"><a href="#{{ title }}">{{ title }}</a></li>
                      {% endfor %}
                    </ul>
                </div>
                <div class="card">
                    <h3>Applicant Requirements</h3>
                    <p>{{ project.applicant_requirements}}</p>
                  </div>
                <div class="card">
                    <h3>Project Timeline</h3>
                    <p>{{ project.time_estimate }} hours</p>
                  </div>     
                </div> <!-- desktop-wrapper-left-->
          
      
        <div class="desktop-wrapper-right">
        <div class="card">
          <div class="positions-header">
              <h3>Positions</h3>
          </div>
          <div class="desktop-flex-wrapper">
          {% if project.position_set %} 
            {% for position in project.position_set.all %}
              <div class="mini-card">
              <h4 id="{{ position.title }}">{{ position.title }}</h4>
              <ul class="ul-list">
                {% for skill in position.skills.all|slice:":12" %}
                <li class="bubble-outline">
                  <a href="{% url 'projects:dashboard' category='skill' q=skill %}">{{ skill }}</a>
                </li>
                {% endfor %}
              </ul>
              <div class="position-description">{{ position.description|truncatewords:26 }}</div>
          
              <!-- Filled -->
              {% if position.status == 'F' %}
              <a class="bubble-dark" style="cursor:not-allowed">Position Filled</a>
    
              <!-- Empty-->
              {% else %}
              {% already_applied position as var %}
              {% if var == 'U' %}
              <a class="bubble-dark" style="cursor:not-allowed">You've applied.</a>
              {% elif var == 'R' %}
              <a class="bubble-dark" style="cursor:not-allowed">You can't apply again</a>
              {% else %}
              <a class="bubble-dark apply-button" pk="{{ position.id }}" id="apply-button-{{ position_pk }}"
                data-url="{% url 'projects:newapp' %}">Apply</a>
              {% endif %}
              {% endif %}
            </div>
            {% endfor %}
            {% else %}
            <div class="mini-card">
              <p>there are currently no positions</p>
            </div>
            {% endif %}
            <div class="position-card hidden"></div>
            <div class="position-card hidden"></div>
        </div>
      </div>
    </div> <!-- /desktop-wrapper-right-->
  </div> <!-- /desktop-wrapper -->
</div> <!-- /bounds -->
{% endblock %}

{% block js %}
{{ block.super }}

<!-- Apply button -->
<script>
$(".apply-button").click(function () {

    // get the csrf token for ajax request  
    
    function getCookie(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie !== '') {
          var cookies = document.cookie.split(';');
          for (var i = 0; i < cookies.length; i++) {
              var cookie = cookies[i].trim();
              // Does this cookie string begin with the name we want?
              if (cookie.substring(0, name.length + 1) === (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
              }
          }
      }
      return cookieValue;
  }
  var csrftoken = getCookie('csrftoken');

  button = $(this)
  var dataurl = $(this).attr("data-url");
  var position_pk = $(this).attr("pk");
  console.log(position_pk, dataurl)

  function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }
  $.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
  });

  $.ajax({
        url: dataurl,
        data: {
          "position_pk": position_pk
        },
        dataType: 'json',
        method: 'POST',
        success: function (data) {
          console.log(data);
          if (data.success) {
            button.replaceWith('<a class="bubble-dark">Applied!</a>');
          } else {
          }
        }
      });
});
</script>

{% endblock %}

socialteambuilder/projects/templates/projects/project_confirm_delete.html
{% extends 'layout.html' %}

{% block body %}
<div class="bounds">
    <div class="card">
        <form method="post">{% csrf_token %}
            <div class="flex-v-container">
                    <h2>Delete project?</h2>
                    <p style="text-align: center">Are you sure you want to delete project <b>{{ object }}</b>? Deleting this project will remove all related positions, including "past projects" records for users that have worked on this project.</p>
                    <div class="center-button-container">
                    <input class="bubble-dark" type="submit" value="Delete">
                    <a class="bubble-dark" href="{% url 'projects:project' slug=object.slug %}">Cancel</a>
                    </div>
            </div>
        </form>
        
    </div>
</div>
{% endblock %}