socialteambuilder/accounts/urls.py
# accounts/urls.py

from django.urls import path, re_path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.Register.as_view(), name="register"),
    path('login/', views.LogIn.as_view(), name='login'),
    re_path('check-inbox/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', views.CheckInbox.as_view(), name="check_inbox"),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    path('updateuser/', views.update_user, name="updateuser"),
    path('profile/<int:pk>/', views.Profile.as_view(), name="profile"),
]

socialteambuilder/projects/urls.py
# project urls.py

from django.urls import path, re_path
from . import views

app_name = 'projects'

urlpatterns = [
    path('search/', views.SearchBar.as_view(), name='searchbar'),
    path('dashboard/<category>/<q>/', views.DashboardView.as_view(), name='dashboard'),
    path('applications/<box>/<category>/<q>/', views.ApplicationsList.as_view(), name='applications'),
    path('ajax/update_app_status/', views.UpdateAppStatus.as_view(), name='update_app_status'),
    path('ajax/create_app/', views.CreateApp.as_view(), name='newapp'),
    path('detail/<slug>/', views.ProjectView.as_view(), name='project'),
    path('delete_project/<slug>/', views.DeleteProject.as_view(), name='delete_project'),
    re_path(r'^create-update-project/(?:(?P<slug>[-a-zA-Z0-9]+)/)?$', views.create_update_project, name="create_update_project"),
]

socialteambuilder/socialteambuilder/urls.py
import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from markdownx import urls as markdownx

from .views import RootRedirect

urlpatterns = [
    path('', RootRedirect.as_view()),
    path('adminymin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('select2/', include('django_select2.urls')),
    path('markdownx/', include(markdownx))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

socialteambuilder/accounts/models.py
from django.conf import settings
from django.core.files.storage import default_storage
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
)

from django.db import models


class UserManager(BaseUserManager):
    """Custom manager for the User model
    """

    def create_user(self, email, first_name, password=None, **kwargs):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        use_in_migrations = True

        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name
        )
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, first_name, password=None, **kwargs):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            first_name=first_name,
        )
        user.is_active = True
        user.is_admin = True
        user.save()
        return user


class User(AbstractBaseUser):
    """Custom model for users
    """
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    about = models.TextField(max_length=2500)
    avatar = models.ImageField(
        default="default_avatars/blank.png", 
        upload_to="avatars"
    )
    skills = models.ManyToManyField(
        "Skill", related_name="users")  # on delete issues?
    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', ]

    def __str__(self):
        if not self.first_name:
            return self.email
        return self.first_name + " " + self.last_name

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.is_admin


class Skill(models.Model):
    """Model for a skill that can be shared by users and positions
    """
    name = models.CharField(max_length=255, unique=True)
    
    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.name.lower()
        return super(Skill, self).save(*args, **kwargs)


class PortfolioProject(models.Model):
    """Model representing a website that the user has built
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="portfolio_projects"
    )
    name = models.CharField(max_length=255, unique=True)
    url = models.URLField()

    def __str__(self):
        return self.name

socialteambuilder/accounts/views.py
# accounts/views.py
from django.utils import timezone

from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import EmailMessage
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.views.generic import (
    TemplateView,
    CreateView,
    DetailView
)
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_bytes
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_encode
from django.utils.http import urlsafe_base64_decode

from projects.forms import SearchBarForm
from projects.models import Application
from projects.views import CustomLoginRequired

from .forms import (
    MyAuthenticationForm,
    UserCreationForm,
    UserUpdateForm,
    NewPortfolioProjectFormset,
    AvatarForm
)
from .models import PortfolioProject

User = get_user_model()


class AccountActivationTokenGenerator(PasswordResetTokenGenerator):
    """Custom token generator for users to use for one-time account
    activation
    """

    def _make_hash_value(self, user, timestamp):
        return (
            str(user.pk) + str(timestamp) + str(user.is_active)
        )


account_activation_token = AccountActivationTokenGenerator()


class Register(SuccessMessageMixin, CreateView):
    """View for registering users. Confirmation email and token is 
    delivered from this view.
    """
    form_class = UserCreationForm
    success_url = reverse_lazy('projects:dashboard', kwargs= {'q': 'all', 'category': 'all'})
    success_message = "You're registered!"
    template_name = 'accounts/register.html'


    def form_valid(self, form):
        if settings.USE_TOKEN_AUTH_WITH_DUMMY_INBOX:
            user = form.save(commit=False)
            user.is_active = False
            user.last_login = timezone.now()
            user.save()
            current_site = get_current_site(self.request)
            to_email = form.cleaned_data.get('email')
            subject = 'Activate Your Social Team Builder Account'
            token = account_activation_token.make_token(user)
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            message = render_to_string('accounts/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': uid,
                'token': token,
            })
            email = EmailMessage(
                subject, message, to=[to_email]
            )
            email.send()
            success_message = "Check your inbox!"
            self.success_url = reverse_lazy('accounts:check_inbox', kwargs={
            'token': token
            })

        else:
            user = form.save(commit=False)
            user.is_active = True
            user.save()

        return super().form_valid(form)


class CheckInbox(TemplateView):
    """View for registration success message
    """
    template_name = "accounts/check_inbox.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['domain'] = get_current_site(self.request)
        context['uid'] = urlsafe_base64_encode(force_bytes(self.request.user.pk))
        context['token'] = kwargs['token']
        return context

def activate(request, uidb64, token):
    """View for handling the verification of token kwarg. If valid, the
    user's active status is set to True
    """
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.success(
            request, "Your account has been confirmed and activated!")
        return HttpResponseRedirect(reverse('accounts:updateuser'))
    else:
        return render(request, 'accounts/failed_activation.html')


class LogIn(SuccessMessageMixin, LoginView):
    """View for handling logging in of user
    """
    form_class = MyAuthenticationForm
    
    def get_success_message(self, cleaned_data):
        super().get_success_message(cleaned_data)
        return 'Welcome back, {}!'.format(self.request.user.first_name)

    def get_current_user(self):
        return self.request.user.first_name


@login_required()
def update_user(request):
    """View for handling the editing of a user instance
    """
    user = request.user
    instance = User.objects.get(id=user.id)
    avatar_form = AvatarForm(instance=instance)
    user_form = UserUpdateForm(instance=instance)
    project_formset = NewPortfolioProjectFormset(
        queryset=PortfolioProject.objects.filter(user=user)
    )
    # get user's accepted applications from completed projects
    applications = Application.objects.filter(
        user=user,
        status='A',
        position__project__status='C'
    ).select_related(
        'position__project'
    )

    if request.method == 'POST':
        if request.is_ajax():
            avatar_form = AvatarForm(request.POST, request.FILES, instance=instance)
            if avatar_form.is_valid():
                user.avatar = request.FILES['id_avatar']
                print("avatar_form is valid and saving: ", user.avatar)
                user.save()
                return HttpResponse(status=200)
            return HttpResponse(status=400)
        else:
            user_form = UserUpdateForm(request.POST, request.FILES, instance=user)
            project_formset = NewPortfolioProjectFormset(
                request.POST,
                queryset=PortfolioProject.objects.filter(user=user)
            )
            print('----------------')
            print(project_formset.data)
            if user_form.is_valid() and project_formset.is_valid():
                user_form.save() 
                projects = project_formset.save(commit=False)
                for project in projects:
                    project.user = user
                    project.save()
                project_formset.save()

                messages.success(request, 'Profile updated successfully!')
                return HttpResponseRedirect(reverse('accounts:profile', kwargs={'pk': user.pk}))
        

    context = {
        'searchform': SearchBarForm(),
        'user_form': user_form,
        'project_formset': project_formset,
        'applications': applications,
        'avatar_form': avatar_form
    }
    return render(request, 'accounts/edit_profile.html', context)


class Profile(CustomLoginRequired, DetailView):
    """View for the detail of user's information
    """
    model = User
    template_name = "accounts/profile.html"
    context_object_name = "user_profile"
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['searchform'] = SearchBarForm()
        # get user's accepted applications from completed projects
        context['applications'] = Application.objects.filter(
            user=self.request.user,
            status='A',
            position__project__status='C'
        )
        return context

socialteambuilder/accounts/templates/accounts/account_activation_email.html
{% autoescape off %}
Hi {{ user.first_name }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}

Thanks,

Social Team Builder
{% endautoescape %}

socialteambuilder/accounts/templates/accounts/check_inbox.html
{% extends 'layout.html' %}

{% block body %}
<div class="bounds">
    <div class="check-inbox">
        <h2>You're Almost There!</h2>
        <p>We've sent an activation token to your inbox. Check your inbox and follow the link to complete your registartion.
        </p>
    </div>
</div>
{% endblock %}

socialteambuilder/accounts/templates/accounts/confirm_email_template.html
{% autoescape off %}
<!--reconfigure with html/django tags for production-->

Hi {{ user.first_name }}, 

Please follow the link below to confirm your registration.

{{ domain }}accounts/activate/{{ user_pk }}/{{ token }}

Thanks,

Social Team Builder

{% endautoescape %}

socialteambuilder/accounts/templates/accounts/edit_profile.html
{% extends 'layout.html' %}

{% load static %}

{% block messages %}
{{ block.super }}
{% endblock %}

{% block css %}
<link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

{{ avatar_form.media.css }}
{{ avatar_form.media.js }}

{% endblock %}

{% block body %}

<!-- Form (all forms) -->
<form method="POST" id="userform_and_projectforms" enctype="multipart/form-data" action="">
{% csrf_token %}

<div class="bounds">

<div class="top-button-container">
        <input type="submit" class="bubble-dark" action="" value="Save Changes">
</div>


{% if user_form.errors or project_formset.errors %}
<div class="error-wrapper">
    <i class="fas fa-exclamation-circle fa-lg"></i>
    {% for error in user_form.errors %}
    {{error}}
    {% endfor %}
    {% for error in project_formset.errors %}
    {{error}}
    {% endfor %}
</div>
{% endif %}

        
<h2>Edit Profile</h2>
<div class="desktop-wrapper">
    <div class="desktop-wrapper-left">
<!-- Avatar -->
<div class="avatar-wrapper">
    <label class="avatar-label" data-toggle="tooltip" title="" data-original-title="Change">
        <img name="id_avatar" id="id_avatar" class="avatar-large" src="{{ user.avatar.url }}"
            alt="avatar" />
        <input type="file" class="sr-only" id="input" name="image" accept="image/*" hidden="True">
    <div class="plus-wrapper">
        <i class="fas fa-plus-circle fa-2x"></i>
    </div>
    </label>
</div>

  
<!-- /Avatar -->

  <!-- User general info -->
  {{ user_form.media }}
<div class="card">
    {{ user_form.first_name }}
    {{ user_form.last_name }}
</div>
    
<div class="card">
    {{ user_form.about }}
    {{ user_form.skills }}
</div>    
</div>


    <div class="desktop-wrapper-right">
        <div class="card">
      <h4 class="center-text-wrapper">My Portfolio</h4>
      <div class="position-edit-cards">
        <!-- Portfolios -->
        {{ project_formset.management_form }}
        {% for form in project_formset %}
        <div class="mini-card position-edit-card" style="display:block">
          {{ form.id }}
          {{ form.name }}
          {{ form.url }}
          <span style="display:none">
            {{ form.DELETE }}
          </span>
          {% for hidden in form.hidden_fields %}
          {{ hidden }}
          {% endfor %}
          <div class="top-button-container">
                <a class="bubble-dark remove-form" id="remove_form"><i class="fas fa-trash-alt"></i> remove</a>
          </div>
        </div>
        {% endfor %}
    </div>
        <div class="top-button-container">
                <a class="bubble-dark" id="add_form"><i class="fas fa-plus"></i> add</a>
          </div>
    </div>
</div>
      <!-- /Portfolios -->

      <!-- Add portfolio form -->

        <!-- /Add portfolio form -->

      <!-- Empty form to clone -->
      <div id="empty_form" style="display:none">
            <div class="mini-card position-edit-card" style="display:block">
              {{ project_formset.empty_form.id }}
              {{ project_formset.empty_form.name }}
              {{ project_formset.empty_form.url }}
              <span style="display:none">
                {{ project_formset.empty_form.DELETE }}
              </span>
              {% for hidden in project_formset.empty_form.hidden_fields %}
              {{ hidden }}
              {% endfor %}
              <div class="top-button-container">
                  <a class="bubble-dark remove-form" id="remove_form"><i class="fas fa-trash-alt"></i> remove</a>
              </div>
    
          </div>
          </div>
          <!-- /Empty form to clone -->
      
      
    </div>
  
  </form>
  <!-- /Form -->

</div>
</div>

<!--avatar modal start-->
<div class="modal_container">
    <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalLabel">Crop Avatar</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true"></span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="img-container">
                        <img id="image" src="{{ user.avatar.url }}">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="bubble-dark button-reset" data-dismiss="modal">Cancel</button>
                    <button type="button" class="bubble-dark button-reset" id="crop">Crop</button>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<!--avatar modal end-->

<!-- Skills js and css in body, only works outside of js and css blocks -->
{{ user_form.media.js }}
{{ user_form.media.css }}

{% endblock %}

{% block js %}
{{ block.super }}

<!-- Select 2 initialization for skills input -->
<script>
    $('#id_skills').select2({
        multiple: true,
        tags: true
      });
    
    // Skills container width correction
    skillsContainer = document.getElementById('id_skills').nextSibling;
    skillsContainer.style.width = '100%';
</script>

<!-- Cropper JS & Bootstrap modal -->
<script>
window.addEventListener('DOMContentLoaded', function () {
    var avatar = document.getElementById('id_avatar');
    var image = document.getElementById('image');
    var input = document.getElementById('input');
    var $progress = $('.progress');
    var $progressBar = $('.progress-bar');
    var $alert = $('.alert');
    var $modal = $('#modal');
    var cropper;

    input.addEventListener('change', function (e) {
        var files = e.target.files;
        var done = function (url) {
            input.value = '';
            image.src = url;
            $alert.hide();
            $modal.modal('show');
        };
        var reader;
        var file;
        var url;

        if (files && files.length > 0) {
            file = files[0];

            if (URL) {
                done(URL.createObjectURL(file));
            } else if (FileReader) {
                reader = new FileReader();
                reader.onload = function (e) {
                    done(reader.result);
                };
                reader.readAsDataURL(file);
            }
        }
    });

    $modal.on('shown.bs.modal', function () {
        cropper = new Cropper(image, {
            aspectRatio: 1,
            viewMode: 3,
        });
    }).on('hidden.bs.modal', function () {
        cropper.destroy();
        cropper = null;
    });

    document.getElementById('crop').addEventListener('click', function () {
        var initialAvatarURL;
        var canvas;

        $modal.modal('hide');

        if (cropper) {
            canvas = cropper.getCroppedCanvas({
            });
            initialAvatarURL = avatar.src;
            avatar.src = canvas.toDataURL('image/jpeg', 1);
            $progress.show();
            $alert.removeClass('alert-success alert-warning');
            canvas.toBlob(function (blob) {
                var formData = new FormData();

                function getCookie(name) {
                    var cookieValue = null;
                    if (document.cookie && document.cookie !== '') {
                        var cookies = document.cookie.split(';');
                        for (var i = 0; i < cookies.length; i++) {
                            var cookie = cookies[i].trim();
                            // Does this cookie string begin with the name we want?
                            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                break;
                            }
                        }
                    }
                    return cookieValue;
                }
                var csrftoken = getCookie('csrftoken');

                function csrfSafeMethod(method) {
                    // these HTTP methods do not require CSRF protection
                    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
                }

                formData.append('id_avatar', blob, 'new_avatar.jpg');
                $.ajaxSetup({
                    beforeSend: function (xhr, settings) {
                        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                            xhr.setRequestHeader("X-CSRFToken", csrftoken);
                        }
                    }
                });

                $.ajax('', {
                    method: 'POST',
                    data: formData,
                    processData: false,
                    contentType: false,


                    xhr: function () {                        
                        var xhr = new XMLHttpRequest();
                        console.log("ajax request created");

                        xhr.upload.onprogress = function (e) {
                            var percent = '0';
                            var percentage = '0%';

                            if (e.lengthComputable) {
                                percent = Math.round((e.loaded / e.total) * 100);
                                percentage = percent + '%';
                                $progressBar.width(percentage).attr('aria-valuenow', percent).text(percentage);
                            }
                            
                        };
                        return xhr;
                    },
                    
                    success: function () {
                        $alert.show().addClass('alert-success').text('Avatar uploaded successfully!');
                        console.log("Success: avatar uploaded")
                    },

                    error: function () {
                        avatar.src = initialAvatarURL;
                        $alert.show().addClass('alert-warning').text('Error uploading avatar!');
                        console.log("Error: avatar not uploaded");
                    },

                    complete: function () {
                        $progress.hide();
                        console.log("ajax request completed");
                    },
                });
            });
        }
    });
});
</script>


<script>
  // Remove Form Event Listener
  $(".remove-form").click(function() {
    var parent = $(this).parents(".position-edit-card");
    var index = parent.find("input").attr("id")[8];
    $('#id_form-' + index + '-DELETE').attr('checked', 'checked');
    parent.attr("style", "display:none"); 
  })

    // Add new position form
    $('#add_form').click(function() {
        var form_idx = $('#id_form-TOTAL_FORMS').val();
        $('.position-edit-cards').append($('#empty_form').html().replace(/__prefix__/g, form_idx));
        let removeButtons = document.querySelectorAll('.remove-form')
        let lastButton = removeButtons[removeButtons.length-2]
        lastButton.addEventListener('click', function(e) {
          var parent = $(this).parents(".position-edit-card");
          var index = parent.find("input").attr("id")[8];
          $('#id_form-' + index + '-DELETE').attr('checked', 'checked');
          parent.attr("style", "display:none"); 
        })
        $('#id_form-TOTAL_FORMS').val(parseInt(form_idx) + 1);
        var forms = $('.position-edit-cards').find(".position-edit-card").length;
        if (forms > 10) $('#add_form').attr('style', 'display:none');
      });
</script>
{% endblock %}

socialteambuilder/accounts/templates/accounts/failed_activation.html
{% extends 'layout.html' %}

{% block body %}
<div class="bounds">
    <div class="flex-window-container">
        <h2>Token Activation Failed</h2>
        <div class="card">
                <p>The link you have is either incomplete or expired. Please try resetting your password again.</p>
        </div>
        <div class="flex-v-container">
                <a href="{% url 'password_reset' %}">Reset password</a>
        </div>     
    </div>
</div>
{% endblock %}

socialteambuilder/accounts/templates/accounts/profile.html
{% extends 'layout.html' %}

{% load static %}

{% block messages %}
{{ block.super }}
{% endblock %}

{% block css %}
{% endblock %}

{% block body %}
<!-- Secondary nav bar -->
<div class="bounds">
<div class="top-button-container">
      {% if user.id == user_profile.id %}
      <a class="bubble-dark" href="{% url 'projects:applications' box='inbox' category='status' q='u' %}"><i class="far fa-comments"></i> Applications</a>
      {% endif %}
      {% if user.id == user_profile.id %}
      <a class="bubble-dark" href="{% url 'accounts:updateuser' %}"><i class="fas fa-user-edit"></i> Edit</a>
      {% endif %}
  </div>
</div>

<!-- /Secondary nav bar -->
    
<div class="bounds">
<div class="desktop-wrapper">
  <div class="desktop-wrapper-left">
<!-- Avatar -->
<div class="card">

    {% if user_profile.avatar %}
    <img src="{{ user_profile.avatar.url }}" class="avatar-large">
    {% endif %}

  <h2>{{ user_profile }}</h2>
  <div>
    {{ user_profile.about }}
  </div>
</div>

    <!-- Skills -->
    <div class="card">
        <h4>My Skills</h4>
        <ul class="ul-list">
          {% for skill in user_profile.skills.all %}
              <li class="bubble-outline"><a href="{% url 'projects:dashboard' category='skill' q=skill %}"><span
                class="skill-button">{{ skill }}</span></a></li>     
          {% endfor %}
          <li class="bubble-outline"><a href="{% url 'projects:dashboard' category='skills' q='my-skills' %}">projects that match your skills</a></li>
        </ul>
      </div>

      <!-- /Skills -->

       <!-- Portfolio projects -->
  <div class="card">
      <h4>My Portfolio</h4>
        {% for project in user_profile.portfolio_projects.all %}
        <div class="mini-card">
            <h4>{{ project.name }}</h4>
            <a href="#">{{ project.url }}</a>
        </div>
        {% endfor %}
    </div>
  </div>
    <!-- /Portfolio projects -->
<div class="desktop-wrapper-right">
<div class="card">
  <h4>Past Projects</h4>

  {% if applications %}
  <ul class="">
  {% for application in applications %}
  <li>{{ application.position.title }}, {{ application.position.project }}</li>
  {% endfor %}
  {% else %}
  <p>You haven't completed any projects yet. <a href="{% url 'projects:dashboard' category='all' q='all' %}">See
      open projects!</a></p>
    </ul>
  {% endif %} 
</div>
</div>
</div>
</div>

{% endblock %}

{% block js %}
{{ block.super }}
{% endblock %}

socialteambuilder/accounts/templates/accounts/register.html
{% extends 'layout.html' %}

{% block messages %}
{% endblock %}

{% block body %}
<div class="bounds">
    <div class="flex-window-container">
        <div class="card">
          <div class="center-button-container">
              <h2>Register!</h2>
          </div>
      
      
      <form method="POST">
        {% csrf_token %}
        {{ form }}
        <div class="center-button-container">
            <a class="bubble-dark" href="{% url 'login' %}">Sign In</a>
            <button type="submit" class="bubble-dark">Sign Up</button>
            
        </div>
      </form>
    </div>
    </div>
  </div>
{% endblock %}