socialteambuilder/accounts/urls.py
# accounts/urls.py

from django.urls import path, re_path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.Register.as_view(), name="register"),
    path('login/', views.LogIn.as_view(), name='login'),
    re_path('check-inbox/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', views.CheckInbox.as_view(), name="check_inbox"),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    path('updateuser/', views.update_user, name="updateuser"),
    path('profile/<int:pk>/', views.Profile.as_view(), name="profile"),
]

socialteambuilder/projects/urls.py
# project urls.py

from django.urls import path, re_path
from . import views

app_name = 'projects'

urlpatterns = [
    path('search/', views.SearchBar.as_view(), name='searchbar'),
    path('dashboard/<category>/<q>/', views.DashboardView.as_view(), name='dashboard'),
    path('applications/<box>/<category>/<q>/', views.ApplicationsList.as_view(), name='applications'),
    path('ajax/update_app_status/', views.UpdateAppStatus.as_view(), name='update_app_status'),
    path('ajax/create_app/', views.CreateApp.as_view(), name='newapp'),
    path('detail/<slug>/', views.ProjectView.as_view(), name='project'),
    path('delete_project/<slug>/', views.DeleteProject.as_view(), name='delete_project'),
    re_path(r'^create-update-project/(?:(?P<slug>[-a-zA-Z0-9]+)/)?$', views.create_update_project, name="create_update_project"),
]

socialteambuilder/socialteambuilder/urls.py
import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from markdownx import urls as markdownx

from .views import RootRedirect

urlpatterns = [
    path('', RootRedirect.as_view()),
    path('adminymin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('select2/', include('django_select2.urls')),
    path('markdownx/', include(markdownx))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

socialteambuilder/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Social Team Builder</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONTS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/js/all.min.js" integrity="sha256-+Q/z/qVOexByW1Wpv81lTLvntnZQVYppIL1lBdhtIq0=" crossorigin="anonymous"></script>

  
  <!-- JS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
  <script type="text/javascript" src="{% static 'js/autogrow.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/global.js' %}"></script>


  <!-- Additional
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  {% block css %}
  {% endblock %}

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="{% static 'sass/css/style.css' %}">

<!-- Nav Bar -->
</head>
<body>
  <header class="header">
    <div class="bounds">
      <div class="flex-h-container">   
          <a class="logo" href="{% url 'projects:dashboard' category='all' q='all' %}"><i class="fab fa-connectdevelop fa-2x"></i> S-Team Builder</a>
          <div class="flex-h-container">
            {% if user.is_authenticated %}
                <a href="{% url 'accounts:profile' pk=user.id %}">
                <img src="{{ user.avatar.url }}" alt="avatar" class="avatar-small" href="{% url 'accounts:profile' pk=user.id %}">
                </a>
            {% endif %}         
              <div>
                {% if user.is_authenticated %}
                    <a class="bubble-dark" href="{% url 'logout' %}">Sign Out</a>
                {% else %}
                    <a class="bubble-dark" href="{% url 'accounts:register' %}">Sign Up</a>
                    <a class="bubble-dark" href="{% url 'login' %}">Sign In</a>
                {% endif %}
              </div>
          </div>        
    </div>
    </div>
  </header>

  {% if searchform %}
  <div class="bounds">  
      <div class="search-bar">
          <form method="GET" action={% url 'projects:searchbar' %} id="search-bar">
              {% csrf_token %}
              {{ searchform.q }}
              <button type="submit">
              <i class="fas fa-search fa-lg"></i>
              </button>
          </form>
        </div>
    </div>
  {% endif %}
<!-- /Nav Bar -->

{% block body %}
{% endblock %}

 <!-- Message Container -->
 <!-- {% if messages %} -->
<div class="message-container">
  <ul>
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
</div>


 <!-- {% endif %} -->
<!-- /Message Container -->

</body>

{% block js %}


{% endblock %}

</html>